# Generated by Django 4.1.3 on 2022-12-01 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_envoi", models.DateField(default=None)),
                ("relances", models.IntegerField(default=0)),
                ("date_relance", models.DateField(default=None)),
                ("date_entretien", models.DateField(default=None)),
                ("comments", models.TextField(max_length=300)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("OK", "Ok"),
                            ("KO", "Ko"),
                            ("En attente", "Ny"),
                            ("A recontacter", "Ar"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=64)),
                ("tel", models.IntegerField()),
                ("linkedin", models.URLField(max_length=64)),
                ("comments", models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Prospect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job", models.CharField(max_length=64)),
                ("company", models.CharField(max_length=64)),
                ("post", models.URLField(max_length=64)),
                ("website", models.URLField(max_length=64)),
                ("email", models.EmailField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Letter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("you", models.TextField(max_length=300)),
                ("me", models.TextField(max_length=300)),
                ("us", models.TextField(max_length=300)),
                (
                    "candidature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="letter_candidature",
                        to="jobtable.candidature",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="candidature",
            name="prospect",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidature_prospect",
                to="jobtable.prospect",
            ),
        ),
    ]
